name: Reusable ACR Build and Push workflow

on:
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
      image-name:
        required: true
        type: string
      app-folder-path:
        required: true
        type: string

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env-name }}

    steps:
      - name: Log in with Azure (Federated Credentials)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ vars.ACR_NAME }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push to ACR
        run: |
          echo "Building image [${{ inputs.image-name }}] for environment [${{ inputs.env-name }}]"
          cd ${{ inputs.app-folder-path }}
          docker build . -t ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.image-name }}:${{ github.sha }}
          docker push ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.image-name }}:${{ github.sha }}
          echo "Image pushed: ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.image-name }}:${{ github.sha }}"
